# Generated by Django 6.0.2 on 2026-02-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
