# Generated by Django 6.0.2 on 2026-03-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_enrollment_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='mailbox_assigned',
            field=models.BooleanField(default=False, help_text='Is digital mailbox assigned to this student?'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='sub_subjects',
            field=models.CharField(blank=True, help_text='e.g., Algebra, Optics', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='subclass',
            field=models.CharField(blank=True, help_text='e.g., Section A, Batch 1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='subjects',
            field=models.CharField(blank=True, help_text='e.g., Maths, Physics', max_length=255, null=True),
        ),
    ]
