# Generated by Django 6.0.2 on 2026-03-03 13:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollments', '0003_enrollment_mailbox_assigned_enrollment_sub_subjects_and_more'),
        ('students', '0002_student_beliefs_student_experience_student_height_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_at'], 'verbose_name': 'Student Enrollment'},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='fee_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Fully Paid'), ('PARTIAL', 'Partial / Installment')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='mailbox_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active / Show'), ('INACTIVE', 'Inactive / Hide'), ('SUSPENDED', 'Suspended'), ('COMPLETED', 'Course Completed')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='storage_limit_mb',
            field=models.IntegerField(default=500, help_text='Allocated storage in MB'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='valid_to',
            field=models.DateTimeField(blank=True, help_text='Expiry date of course access', null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='class_name',
            field=models.CharField(blank=True, help_text='Level: e.g. Secondary', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='mailbox_assigned',
            field=models.BooleanField(default=False, help_text='Is digital mailbox assigned?'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='sub_subjects',
            field=models.CharField(blank=True, help_text='e.g. Quantum Mechanics', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='subclass',
            field=models.CharField(blank=True, help_text='Section: e.g. Section A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='subjects',
            field=models.CharField(blank=True, help_text='e.g. Physics, Chemistry', max_length=255, null=True),
        ),
    ]
