# Generated by Django 6.0.2 on 2026-04-11 20:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_student_parent'),
        ('teachers', '0004_teacher_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('service_type', models.CharField(choices=[('course_access', 'Course Access'), ('assignment_exam_access', 'Assignment & Exam Access'), ('exam', 'Exam Access'), ('course', 'Course'), ('hostel', 'Hostel Fee'), ('library', 'Library Access'), ('transport', 'Transport Fee'), ('custom', 'Custom Service')], default='custom', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_chargeable', models.BooleanField(default=True, help_text='If False, service is free')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility to students')),
                ('validity_days', models.IntegerField(default=365, help_text='Access validity after payment (days)')),
                ('icon', models.CharField(default='BookOpen', help_text='Lucide icon name', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Catalog',
                'verbose_name_plural': 'Service Catalog',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentServicePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name_snapshot', models.CharField(max_length=200)),
                ('service_price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_type_snapshot', models.CharField(default='custom', max_length=50)),
                ('invoice_number', models.CharField(default='', max_length=100, unique=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=150)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=150)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet'), ('emi', 'EMI'), ('other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.servicecatalog')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_payments', to='students.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Payment',
                'verbose_name_plural': 'Student Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], default='savings', max_length=20)),
                ('upi_id', models.CharField(blank=True, help_text='Optional UPI ID', max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Admin verifies bank details')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Bank Details',
            },
        ),
        migrations.CreateModel(
            name='TeacherSalaryPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(default='', max_length=100, unique=True)),
                ('month', models.CharField(help_text='e.g. April 2026', max_length=20)),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_holder_name', models.CharField(blank=True, max_length=200)),
                ('payment_mode', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('upi', 'UPI'), ('cheque', 'Cheque')], default='bank_transfer', max_length=30)),
                ('transaction_reference', models.CharField(blank=True, help_text='UTR/Cheque No/UPI Ref', max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('hold', 'On Hold')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payments_made', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Salary Payment',
                'verbose_name_plural': 'Teacher Salary Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_access', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_records', to='payments.servicecatalog')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.studentservicepayment')),
            ],
            options={
                'verbose_name': 'Service Access',
                'verbose_name_plural': 'Service Access Records',
                'unique_together': {('user', 'service')},
            },
        ),
    ]
