# Generated by Django 6.0.2 on 2026-04-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecatalog',
            name='badge_text',
            field=models.CharField(blank=True, help_text="e.g. '75% off', 'Best Value'", max_length=50),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='color',
            field=models.CharField(default='#4f46e5', help_text='Card accent hex color', max_length=20),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of feature strings shown on the card'),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='is_popular',
            field=models.BooleanField(default=False, help_text="Show 'Most Popular' badge on card"),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount (for strikethrough display)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='icon',
            field=models.CharField(default='BookOpen', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='is_chargeable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='validity_days',
            field=models.IntegerField(default=365),
        ),
    ]
