# Generated by Django 6.0.2 on 2026-05-04 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_servicecatalog_badge_text_servicecatalog_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecatalog',
            name='badge_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='color',
            field=models.CharField(default='#4f46e5', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='service_type',
            field=models.CharField(choices=[('course_access', 'Course Access'), ('assignment_exam_access', 'Assignment & Exam Access'), ('hostel', 'Hostel Fee'), ('library', 'Library Access'), ('transport', 'Transport Fee'), ('custom', 'Custom Service')], default='custom', max_length=50),
        ),
    ]
