# Generated by Django 6.0.2 on 2026-03-22 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSkillsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_school', models.CharField(blank=True, max_length=255, null=True)),
                ('tenth_year', models.IntegerField(blank=True, null=True)),
                ('tenth_percentage', models.FloatField(blank=True, null=True)),
                ('twelfth_school', models.CharField(blank=True, max_length=255, null=True)),
                ('twelfth_year', models.IntegerField(blank=True, null=True)),
                ('twelfth_percentage', models.FloatField(blank=True, null=True)),
                ('graduation_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('graduation_college', models.CharField(blank=True, max_length=255, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('graduation_percentage', models.FloatField(blank=True, null=True)),
                ('extra_certifications', models.TextField(blank=True, null=True)),
                ('technical_skills', models.TextField(blank=True, help_text='Comma separated skills', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalMedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, help_text='e.g. A+, O-', max_length=5, null=True)),
                ('height_cm', models.FloatField(blank=True, help_text='Height in centimeters', null=True)),
                ('weight_kg', models.FloatField(blank=True, help_text='Weight in kilograms', null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('chronic_diseases', models.TextField(blank=True, help_text='Any medical history or allergies', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalJobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_experience_years', models.IntegerField(default=0)),
                ('total_experience_months', models.IntegerField(default=0)),
                ('last_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('last_salary', models.CharField(blank=True, max_length=50, null=True)),
                ('reason_for_leaving', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialHumanityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_donation_history', models.TextField(blank=True, help_text='Dates and places of donation', null=True)),
                ('ngo_social_work', models.TextField(blank=True, help_text='NGO names or volunteer work', null=True)),
                ('awards_achievements', models.TextField(blank=True, help_text='Special recognitions', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
