# Generated by Django 6.0.2 on 2026-02-09 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='e.g., 2024-2025', max_length=9)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True)),
                ('category', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS')], default='General', max_length=20)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('roll_number', models.CharField(max_length=20)),
                ('student_class', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=10)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('fee_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_mobile', models.CharField(max_length=15)),
                ('secondary_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('current_address', models.TextField()),
                ('city', models.CharField(default='Meerut', max_length=50)),
                ('state', models.CharField(default='Uttar Pradesh', max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('aadhar_scan', models.FileField(blank=True, null=True, upload_to='students/docs/')),
                ('tc_scan', models.FileField(blank=True, null=True, upload_to='students/docs/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.academicsession')),
            ],
        ),
    ]
