# Generated by Django 6.0.2 on 2026-02-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='beliefs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='height',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hobbies',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='marital_status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Other', 'Other')], default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='marksheet_scan',
            field=models.FileField(blank=True, null=True, upload_to='students/docs/'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='place_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Non-Registered', 'Non-Registered'), ('Both', 'Both'), ('None', 'None')], default='Registered', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='service_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated'), ('Hibernation', 'Hibernation'), ('Hidden', 'Hidden')], default='Active', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='subplace_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='subservice_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='user_group',
            field=models.CharField(default='Service Seekers', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='user_subgroup',
            field=models.CharField(default='Students', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='validity_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='validity_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='virtual_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
