# Generated by Django 6.0.2 on 2026-03-22 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
        ('students', '0003_rename_student_photo_student_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Link this student to a parent profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='parents.parentprofile'),
        ),
    ]
