# Generated by Django 6.0.2 on 2026-02-13 06:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feetransaction',
            options={'ordering': ['-payment_date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='feetransaction',
            old_name='penalty_paid',
            new_name='due_amount',
        ),
        migrations.RemoveField(
            model_name='feetransaction',
            name='installment',
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], default='Paid', max_length=20),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='student_class',
            field=models.CharField(default='10-A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='student_name',
            field=models.CharField(default='Unknown Student', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='penalty_applied',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feetransaction',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feetransaction',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI / Online', 'UPI / Online'), ('Cheque', 'Cheque')], default='Cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='feetransaction',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='students.student'),
        ),
        migrations.AlterField(
            model_name='feetransaction',
            name='transaction_id',
            field=models.CharField(help_text='Unique Receipt No (e.g. REC-2026-101)', max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='FeeLedger',
        ),
    ]
