# Generated by Django 6.0.2 on 2026-02-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_feetransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetransaction',
            name='discount_approved_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='feetransaction',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI / Bank Transfer', 'UPI / Bank Transfer'), ('Cheque', 'Cheque'), ('Online Gateway (Secure)', 'Online Gateway (Secure)'), ('Online Gateway', 'Online Gateway')], default='Cash', max_length=50),
        ),
    ]
