# Generated by Django 6.0.2 on 2026-04-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_feetransaction_discount_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetransaction',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='e.g. 18.00 for 18% GST', max_digits=5),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Auto-generated GST Invoice No.', max_length=100, null=True, unique=True),
        ),
    ]
