# Generated by Django 6.0.2 on 2026-02-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_natureofservice_servicecharge_serviceprovidergroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_allocated_mb', models.FloatField(default=5000.0)),
                ('downloaded_mb', models.FloatField(default=0.0)),
                ('uploaded_mb', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('notice_type', models.CharField(choices=[('General', 'General'), ('Holiday', 'Holiday'), ('Event', 'Event'), ('Meeting', 'Meeting')], max_length=50)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20, unique=True)),
                ('ticket_type', models.CharField(choices=[('Complain', 'Complain'), ('Enquiry', 'Enquiry'), ('Feedback', 'Feedback')], max_length=50)),
                ('user_name', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Read', 'Read')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
