# Generated by Django 6.0.2 on 2026-02-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_mailboxstat_notice_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Super Admin', max_length=150)),
                ('action_type', models.CharField(choices=[('Save', 'Save'), ('Share', 'Share'), ('Send', 'Send'), ('Copy', 'Copy'), ('Paste', 'Paste'), ('Bulk Action', 'Bulk Action'), ('Delete', 'Delete'), ('Update', 'Update')], max_length=50)),
                ('module_affected', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Anonymous', max_length=150)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('duration_calculated', models.CharField(blank=True, max_length=255, null=True)),
                ('is_live', models.BooleanField(default=True)),
            ],
        ),
    ]
