# Generated by Django 6.0.2 on 2026-03-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_actionlog_systemsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Shiv Adda', max_length=255)),
                ('default_language', models.CharField(default='English', max_length=50)),
                ('default_currency', models.CharField(default='INR', max_length=10)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('show_weather', models.BooleanField(default=True)),
                ('default_weather_location', models.CharField(default='New Delhi, India', max_length=100)),
                ('enable_file_converter', models.BooleanField(default=True, help_text='Turn ON/OFF File Converter Tool')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Turn ON to lock frontend for maintenance')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Setting',
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
