# Generated by Django 6.0.2 on 2026-03-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_globalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleBinItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_model_name', models.CharField(max_length=100)),
                ('original_object_id', models.CharField(max_length=100)),
                ('object_repr', models.CharField(help_text='Name of the deleted item', max_length=255)),
                ('object_data', models.JSONField(help_text='Serialized data for restore')),
                ('deleted_by', models.CharField(default='System / Admin', max_length=150)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recycle Bin Item',
                'verbose_name_plural': 'Recycle Bin Items',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
