# Generated by Django 6.0.2 on 2026-03-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_national_identity_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, help_text='Temporary OTP for Login', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_id_code',
            field=models.CharField(blank=True, help_text='Code for Time-Limited Trial/Guest Access', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_id_expiry',
            field=models.DateTimeField(blank=True, help_text='Expiry Date & Time for Temporary ID', null=True),
        ),
    ]
