# Generated by Django 6.0.2 on 2026-04-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_otp_user_temp_id_code_user_temp_id_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Shiv Adda', max_length=255)),
                ('gst_number', models.CharField(blank=True, help_text='Global GST Number for Invoices', max_length=20, null=True)),
                ('global_otp_login', models.BooleanField(default=False, help_text='Turn ON to force OTP for EVERYONE')),
                ('support_email', models.EmailField(default='support@shivadda.com', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_otp_enabled',
            field=models.BooleanField(default=False, help_text='Admin control to enable/disable OTP for this user'),
        ),
    ]
