# Generated by Django 6.0.2 on 2026-05-04 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_systemconfig_user_is_otp_enabled'),
        ('locations', '0005_place_branch_code'),
        ('services', '0007_recyclebinitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='locations.place'),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.IntegerField(default=0, help_text='Rank from 0 to 5 (Mainly for Teachers/HOD)'),
        ),
        migrations.AddField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='users_enrolled', to='services.servicetype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('SCHOOL_ADMIN', 'School Admin'), ('HOD', 'Head of Department'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('SECURITY', 'Security Guard'), ('STAFF', 'Support Staff'), ('AGENT', 'Agent')], default='STUDENT', max_length=50),
        ),
    ]
