# Generated by Django 6.0.2 on 2026-05-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_place_user_rank_user_services_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGEMENT_STAFF', 'Management Staff'), ('HEAD_OF_PLACE', 'Head of Place'), ('TEACHER', 'Teacher'), ('LAB_ASSISTANT', 'Lab Assistant'), ('LIBRARIAN', 'Librarian'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('GUEST', 'Guest'), ('SECURITY', 'Security Guard'), ('HOSTEL_STAFF', 'Hostel Staff'), ('TRANSPORT_STAFF', 'Transport Staff'), ('STAFF', 'Other Staff'), ('AGENT', 'Agent')], default='STUDENT', max_length=50),
        ),
    ]
