# Generated by Django 6.0.2 on 2026-02-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='studentperformance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentperformance',
            name='subject',
        ),
        migrations.RenameField(
            model_name='questionbank',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='subject',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='q_type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('Descriptive', 'Descriptive'), ('True/False', 'True/False')], default='Descriptive', max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=20),
        ),
        migrations.DeleteModel(
            name='AnswerEvaluation',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
        migrations.DeleteModel(
            name='StudentPerformance',
        ),
    ]
