# Generated by Django 6.0.2 on 2026-02-22 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
        ('courses', '0001_initial'),
        ('exams', '0003_questionbank_subject_alter_exam_exam_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='examinee_body',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='paper_set_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='place_of_exam',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='negative_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='question',
            name='option_e',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unattempted_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='correct_option',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='negative_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_e',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='unattempted_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batches.batch'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='marks',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_option',
            field=models.CharField(max_length=10),
        ),
    ]
