# Generated by Django 6.0.2 on 2026-02-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_class_name_exam_examinee_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='paper_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='permission',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='validity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, default='A', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='exam_meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='section',
            field=models.CharField(blank=True, default='A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='q_type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('Descriptive', 'Descriptive'), ('True/False', 'True/False'), ('Both', 'Both'), ('None', 'None')], default='Descriptive', max_length=50),
        ),
    ]
