# Generated by Django 6.0.2 on 2026-02-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_exam_password_exam_paper_id_exam_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='mode_of_exam',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='paper_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='tools_allowed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(blank=True, default='Level 1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_f',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_g',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_h',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='level',
            field=models.CharField(blank=True, default='Level 1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_f',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_g',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_h',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
