# Generated by Django 6.0.2 on 2026-03-17 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_assignment_exam_created_at_exam_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Class 10, BCA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Foundation, Middle, Secondary', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 100 Marks Standard Blueprint', max_length=150)),
                ('total_questions', models.IntegerField(default=100)),
                ('max_marks', models.FloatField(default=100.0)),
                ('positive_mark_per_q', models.FloatField(default=1.0)),
                ('negative_mark_per_q', models.FloatField(default=0.25)),
                ('unattempted_mark_per_q', models.FloatField(default=0.0)),
                ('passing_percentage', models.FloatField(default=33.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='chapter_name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='course',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='negative_marks',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='passing_marks',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
        migrations.RemoveField(
            model_name='question',
            name='negative_marks',
        ),
        migrations.RemoveField(
            model_name='question',
            name='unattempted_marks',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='subject',
        ),
        migrations.AddField(
            model_name='descriptivesubmission',
            name='final_average_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descriptivesubmission',
            name='t1_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descriptivesubmission',
            name='t1_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descriptivesubmission',
            name='t1_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='descriptivesubmission',
            name='t2_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descriptivesubmission',
            name='t2_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descriptivesubmission',
            name='t2_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='descriptivesubmission',
            name='t3_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descriptivesubmission',
            name='t3_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descriptivesubmission',
            name='t3_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='correct_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='incorrect_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='negative_marks_deducted',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='omr_sheet_image',
            field=models.ImageField(blank=True, null=True, upload_to='omr_scans/'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='unattempted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='marks_awarded',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('HOTS', 'HOTS')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_option',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.academicclass'),
        ),
        migrations.AddField(
            model_name='exam',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.academicclass'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.chapter'),
        ),
        migrations.AddField(
            model_name='academicclass',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='exams.educationlevel'),
        ),
        migrations.AddField(
            model_name='exam',
            name='blueprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.examblueprint'),
        ),
        migrations.CreateModel(
            name='LiveQuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mega Live Quiz', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_timer', models.IntegerField(default=0)),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('main_score', models.IntegerField(default=0)),
                ('bonus_score', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='exams.livequizsession')),
            ],
        ),
        migrations.CreateModel(
            name='SubClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Section A, Science Stream, etc.', max_length=100)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclasses', to='exams.academicclass')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='subclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.subclass'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_optional', models.BooleanField(default=False)),
                ('subclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='exams.subclass')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.subject'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.subject'),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.subject'),
        ),
        migrations.CreateModel(
            name='SyllabusUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Unit 1: Mechanics', max_length=200)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='exams.subject')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='exams.syllabusunit'),
        ),
        migrations.AddField(
            model_name='exam',
            name='syllabus_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.syllabusunit'),
        ),
    ]
