# Generated by Django 6.0.2 on 2026-03-17 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_academicclass_chapter_educationlevel_examblueprint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_india_rank', models.IntegerField(blank=True, help_text='All India Rank', null=True)),
                ('state_rank', models.IntegerField(blank=True, help_text='State Level Rank', null=True)),
                ('percentile', models.FloatField(blank=True, help_text='Percentile Score', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='exams.examattempt')),
            ],
        ),
    ]
