# Generated by Django 6.0.2 on 2026-02-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.CharField(help_text='Main Subject', max_length=100)),
                ('qualification', models.CharField(help_text='e.g. M.Sc, B.Ed', max_length=100)),
                ('experience', models.CharField(help_text='e.g. 5 Years', max_length=50)),
                ('designation', models.CharField(default='Assistant Teacher', max_length=100)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
