# Generated by Django 6.0.2 on 2026-02-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(default='General', help_text='e.g. Science, Commerce', max_length=100),
        ),
    ]
