# Generated by Django 6.0.2 on 2026-03-11 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject_class', models.CharField(max_length=100)),
                ('material_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='study_materials/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_email', models.EmailField(max_length=254)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('snippet', models.CharField(blank=True, help_text='Short preview of the mail', max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('folder', models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('drafts', 'Drafts'), ('archive', 'Archive'), ('trash', 'Trash')], default='inbox', max_length=20)),
                ('label', models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('assignments', 'Assignments'), ('parents', 'Parents'), ('general', 'General')], default='general', max_length=20, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('has_attachment', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='mail_attachments/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
