# Generated by Django 6.0.2 on 2026-04-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='whatsapp_group_link',
            field=models.URLField(blank=True, help_text='Paste WhatsApp Invite Link here', max_length=500, null=True),
        ),
    ]
