import React, { useState, useEffect } from "react";
import SidebarModern from "../components/SidebarModern";
import api from "../api/axios";
import toast, { Toaster } from 'react-hot-toast';
import { motion, AnimatePresence } from "framer-motion";
import { 
  DollarSign, Calendar, User, Briefcase, 
  CheckCircle, Clock, Users, TrendingUp, 
  Search, Filter, Download, MoreHorizontal, Activity, Wallet,
  Eye, X, Printer, FileText, ChevronLeft, ChevronRight 
} from "lucide-react"; 

export default function Payroll() {
  const [payments, setPayments] = useState([]);
  const [loading, setLoading] = useState(false);
  const [stats, setStats] = useState({ totalPaid: 0, pendingCount: 0, totalStaff: 0 });
  const [searchTerm, setSearchTerm] = useState("");
  const [hoveredRow, setHoveredRow] = useState(null);
  const [selectedReceipt, setSelectedReceipt] = useState(null);

  const [form, setForm] = useState({
    staff_name: "",
    role: "Teacher",
    amount: "",
    month: new Date().toLocaleString('default', { month: 'long', year: 'numeric' }),
    status: "Paid"
  });

  useEffect(() => { fetchPayments(); }, []);

  const fetchPayments = async () => {
    try {
      const res = await api.get("payroll/");
      setPayments(res.data);
      calculateStats(res.data);
    } catch (err) { console.error(err); }
  };

  const calculateStats = (data) => {
    const paid = data.filter(p => p.status === 'Paid').reduce((acc, curr) => acc + Number(curr.amount), 0);
    const pending = data.filter(p => p.status === 'Pending').length;
    const staff = new Set(data.map(p => p.staff_name)).size;
    setStats({ totalPaid: paid, pendingCount: pending, totalStaff: staff });
  };

  const handlePay = async (e) => {
    e.preventDefault();
    setLoading(true);
    try {
      await api.post("payroll/", form);
      toast.success(`Payment Initiated for ${form.staff_name} 🚀`);
      setForm({ ...form, staff_name: "", amount: "" });
      fetchPayments();
    } catch (error) { toast.error("Transaction Failed ❌"); }
    setLoading(false);
  };

  // 🖨️ FUNCTION: Print Receipt
  const handlePrintReceipt = () => {
    const printWindow = window.open('', '', 'width=600,height=700');
    printWindow.document.write(`
      <html>
        <head>
          <title>Payment Receipt - ${selectedReceipt.staff_name}</title>
          <style>
            body { font-family: 'Segoe UI', sans-serif; padding: 40px; text-align: center; color: #1e293b; }
            .container { border: 2px dashed #cbd5e1; padding: 30px; border-radius: 20px; }
            .header { margin-bottom: 30px; }
            .amount { font-size: 48px; font-weight: 800; color: #4f46e5; margin: 10px 0; }
            .status { color: #16a34a; font-weight: 700; background: #dcfce7; padding: 5px 15px; border-radius: 20px; display: inline-block; }
            .row { display: flex; justify-content: space-between; margin-bottom: 15px; border-bottom: 1px solid #f1f5f9; padding-bottom: 10px; }
            .label { color: #64748b; font-weight: 600; }
            .value { font-weight: 700; }
            .footer { margin-top: 40px; font-size: 12px; color: #94a3b8; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h2>PAYMENT RECEIPT</h2>
              <div class="amount">₹${Number(selectedReceipt.amount).toLocaleString()}</div>
              <div class="status">Payment Successful</div>
            </div>
            <div class="content">
              <div class="row"><span class="label">Transaction ID</span><span class="value">TXN-${selectedReceipt.id}8829</span></div>
              <div class="row"><span class="label">Staff Name</span><span class="value">${selectedReceipt.staff_name}</span></div>
              <div class="row"><span class="label">Role</span><span class="value">${selectedReceipt.role}</span></div>
              <div class="row"><span class="label">Month</span><span class="value">${selectedReceipt.month}</span></div>
              <div class="row"><span class="label">Date</span><span class="value">${new Date(selectedReceipt.payment_date).toLocaleString()}</span></div>
            </div>
            <div class="footer">
              <p>Generated by Shivadda Platform<br>This is a system generated receipt.</p>
            </div>
          </div>
          <script>window.print();</script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  // 📥 FUNCTION: Download Receipt (Text File)
  const handleDownloadReceipt = () => {
    const receiptText = `
========================================
            PAYMENT RECEIPT
========================================

Amount:      ₹${Number(selectedReceipt.amount).toLocaleString()}
Status:      Successful
Date:        ${new Date(selectedReceipt.payment_date).toLocaleString()}

----------------------------------------
Transaction Details:
----------------------------------------
Transaction ID:  TXN-${selectedReceipt.id}8829
Staff Name:      ${selectedReceipt.staff_name}
Role:            ${selectedReceipt.role}
Month:           ${selectedReceipt.month}

========================================
Generated by Shivadda Platform
========================================
    `;
    
    const blob = new Blob([receiptText], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Receipt_${selectedReceipt.staff_name}_${selectedReceipt.month}.txt`;
    link.click();
    window.URL.revokeObjectURL(url);
    toast.success("Receipt Downloaded 📥");
  };

  const filteredPayments = payments.filter(p => 
    p.staff_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    p.role.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="payroll-page-wrapper">
      <div style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, zIndex: 0, pointerEvents: 'none', background: 'radial-gradient(circle at 15% 50%, rgba(99, 102, 241, 0.05), transparent 25%), radial-gradient(circle at 85% 30%, rgba(168, 85, 247, 0.05), transparent 25%)' }}></div>
      <SidebarModern />
      
      <div className="payroll-main-content">
        <Toaster position="top-center" />
        
        {/* Header */}
        <div className="page-header">
            <div>
                <h1 style={{ color: "#0f172a", fontSize: '2rem', fontWeight: '900', letterSpacing: '-1px', margin: '0 0 5px 0' }}>Payroll Hub</h1>
                <p style={{ color: '#64748b', fontSize: '0.95rem', fontWeight: '500', margin: 0 }}>Manage salaries & transactions.</p>
            </div>
            <div className="header-actions">
                <button style={secondaryBtnStyle}><Filter size={16} /> Filter</button>
                <button style={primaryBtnStyle}><Download size={16} /> Export</button>
            </div>
        </div>

        {/* Stats */}
        <div className="stats-grid">
            <div style={heroStatCardStyle}>
                <div style={{ position: 'relative', zIndex: 1, display: 'flex', justifyContent: 'space-between', alignItems: 'start' }}>
                    <div><p style={{ fontSize: '0.85rem', fontWeight: '600', opacity: 0.9, margin: '0 0 5px 0', color: 'rgba(255,255,255,0.9)' }}>Total Disbursed</p><h2 style={{ fontSize: '1.8rem', fontWeight: '800', color: 'white', margin: 0 }}>₹{(stats.totalPaid/1000).toFixed(1)}k</h2></div>
                    <div style={{ background: 'rgba(255,255,255,0.25)', padding: '8px', borderRadius: '10px', backdropFilter: 'blur(5px)' }}><TrendingUp size={20} color="white" /></div>
                </div>
                <div style={{ position: 'relative', zIndex: 1, marginTop: '10px', display: 'flex', alignItems: 'center', gap: '5px', fontSize: '0.8rem', fontWeight: '600', color: 'rgba(255,255,255,0.9)' }}><Activity size={14} /> +12% increase</div>
            </div>
            <div style={glassStatCardStyle}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'start' }}><div><p style={cardLabelStyle}>Pending</p><h2 style={cardValueStyle}>{stats.pendingCount}</h2></div><div style={{ background: '#fff1f2', padding: '8px', borderRadius: '10px' }}><Clock size={20} color="#e11d48" /></div></div>
            </div>
            <div style={glassStatCardStyle}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'start' }}><div><p style={cardLabelStyle}>Active Staff</p><h2 style={cardValueStyle}>{stats.totalStaff}</h2></div><div style={{ background: '#f0f9ff', padding: '8px', borderRadius: '10px' }}><Users size={20} color="#0284c7" /></div></div>
            </div>
        </div>

        {/* ✅ FIXED: Desktop and Mobile Layout for Form vs Table */}
        <div className="content-flex-container">
            
            {/* Form */}
            <div style={glassPanelStyle} className="form-panel">
              <div style={{ borderBottom: '1px solid #f1f5f9', paddingBottom: '15px', marginBottom: '15px', display: 'flex', alignItems: 'center', gap: '10px' }}>
                  <div style={{ background: '#e0e7ff', padding: '8px', borderRadius: '10px' }}><Wallet size={18} color="#4f46e5" /></div>
                  <h3 style={{ fontSize: '1.1rem', fontWeight: '800', color: '#1e293b', margin: 0 }}>Quick Pay</h3>
              </div>
              <form onSubmit={handlePay} style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
                <div style={inputGroupStyle}><label style={labelStyle}>Staff Member</label><input placeholder="Ex. Rahul Sharma" required value={form.staff_name} onChange={e => setForm({...form, staff_name: e.target.value})} style={inputStyle} /></div>
                <div className="grid-2-col">
                    <div style={inputGroupStyle}><label style={labelStyle}>Role</label><select value={form.role} onChange={e => setForm({...form, role: e.target.value})} style={inputStyle}><option value="Teacher">Teacher</option><option value="Staff">Staff</option><option value="Driver">Driver</option></select></div>
                    <div style={inputGroupStyle}><label style={labelStyle}>Amount</label><input type="number" placeholder="₹ 0.00" required value={form.amount} onChange={e => setForm({...form, amount: e.target.value})} style={{...inputStyle, fontWeight: '700'}} /></div>
                </div>
                <div style={inputGroupStyle}><label style={labelStyle}>For Month</label><input placeholder="Select Month" value={form.month} onChange={e => setForm({...form, month: e.target.value})} style={inputStyle} /></div>
                
                <button type="submit" disabled={loading} style={actionGlowBtnStyle}>
                    {loading ? "Processing..." : "Initiate Transfer 💸"}
                </button>
              </form>
            </div>

            {/* Table */}
            <div className="table-panel">
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', background: 'white', padding: '10px 15px', borderRadius: '14px', border: '1px solid #e2e8f0', flexWrap: 'wrap', gap: '10px' }}>
                  <h3 style={{ fontSize: '1rem', fontWeight: '800', color: '#1e293b', margin: 0 }}>History</h3>
                  <div style={{ display: 'flex', alignItems: 'center', background: '#f8fafc', borderRadius: '10px', padding: '5px 10px', border: '1px solid #e2e8f0', flexGrow: 1, maxWidth: '300px' }}>
                    <Search size={14} color="#94a3b8" />
                    <input placeholder="Search records..." value={searchTerm} onChange={e=>setSearchTerm(e.target.value)} style={{border:'none', background:'transparent', outline:'none', fontSize:'0.85rem', marginLeft:'8px', width:'100%'}} />
                  </div>
              </div>
              <div className="table-wrapper">
                  <table style={{ width: "100%", borderCollapse: "separate", borderSpacing: '0 8px', minWidth: '700px' }}>
                    <thead>
                      <tr>
                        <th style={thStyle}>Date</th><th style={thStyle}>Employee</th><th style={thStyle}>Role</th><th style={thStyle}>Amount</th><th style={thStyle}>Status</th><th style={{...thStyle, textAlign:'right'}}>Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      {filteredPayments.map((p) => (
                        <tr key={p.id} style={{...floatingRowStyle, transform: hoveredRow === p.id ? 'translateY(-2px)' : 'none', boxShadow: hoveredRow === p.id ? '0 8px 15px -5px rgba(0,0,0,0.05)' : '0 2px 4px -1px rgba(0,0,0,0.02)'}} onMouseEnter={() => setHoveredRow(p.id)} onMouseLeave={() => setHoveredRow(null)}>
                          <td style={tdStyle}><span style={{fontWeight: '600', color: '#64748b', whiteSpace: 'nowrap'}}>{new Date(p.payment_date).toLocaleDateString('en-US', { day: '2-digit', month: 'short' })}</span></td>
                          <td style={tdStyle}><div style={{ display: 'flex', alignItems: 'center', gap: '10px', whiteSpace: 'nowrap' }}><div style={{...avatarStyle, background: '#f1f5f9', color: '#475569'}}>{p.staff_name.charAt(0)}</div><div><div style={{ fontWeight: '700', color: '#1e293b', fontSize: '0.9rem' }}>{p.staff_name}</div></div></div></td>
                          <td style={tdStyle}><span style={{background: '#f8fafc', padding: '4px 8px', borderRadius: '6px', fontSize: '0.75rem', fontWeight: '600', color: '#475569', whiteSpace: 'nowrap'}}>{p.role}</span></td>
                          <td style={tdStyle}><span style={{fontWeight: '800', color: '#0f172a', fontSize:'0.95rem', whiteSpace: 'nowrap'}}>₹{Number(p.amount).toLocaleString()}</span></td>
                          <td style={tdStyle}><span style={{padding: "4px 10px", borderRadius: "20px", fontSize: "0.75rem", fontWeight: '700', background: p.status === "Paid" ? "#dcfce7" : "#fff1f2", color: p.status === "Paid" ? "#166534" : "#be123c", display: 'inline-flex', alignItems: 'center', gap: '4px', whiteSpace: 'nowrap'}}>{p.status === "Paid" ? <CheckCircle size={10}/> : <Clock size={10}/>}{p.status}</span></td>
                          <td style={{...tdStyle, textAlign: 'right'}}>
                            <button onClick={() => setSelectedReceipt(p)} style={{ background: '#f1f5f9', border: 'none', padding: '6px 10px', borderRadius: '8px', cursor: 'pointer', display: 'inline-flex', alignItems: 'center', gap: '5px', fontSize: '0.75rem', fontWeight: '600', color: '#334155', whiteSpace: 'nowrap' }}><Eye size={14}/> View</button>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                  {filteredPayments.length === 0 && <div style={{ textAlign: "center", padding: "30px", color: "#94a3b8" }}><p>No transactions found.</p></div>}
              </div>
              
              {filteredPayments.length > 0 && (
                <div className="pagination-container" style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '20px', paddingBottom: '20px'}}>
                    <button className="btn-secondary" style={{padding: '8px 16px', fontSize: '0.85rem', display:'flex', alignItems:'center', gap:'5px', cursor:'pointer'}}><ChevronLeft size={16}/> Prev</button>
                    <span style={{fontSize: '0.9rem', color: '#64748b', fontWeight: '600'}}>Page 1 of 1</span>
                    <button className="btn-secondary" style={{padding: '8px 16px', fontSize: '0.85rem', display:'flex', alignItems:'center', gap:'5px', cursor:'pointer'}}>Next <ChevronRight size={16}/></button>
                </div>
              )}

            </div>
        </div>

        {/* 🌟 MODAL (Fully Functional) 🌟 */}
        <AnimatePresence>
            {selectedReceipt && (
                <div style={{ position: 'fixed', inset: 0, zIndex: 50, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(0,0,0,0.4)', backdropFilter: 'blur(5px)' }}>
                    <motion.div initial={{ opacity: 0, scale: 0.9, y: 20 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: 0.9 }} style={{ background: 'white', width: '100%', maxWidth: '400px', borderRadius: '24px', boxShadow: '0 25px 50px -12px rgba(0,0,0,0.25)', overflow: 'hidden', margin: '20px', maxHeight: '90vh', display: 'flex', flexDirection: 'column' }}>
                        <div style={{ background: 'linear-gradient(135deg, #0f172a 0%, #334155 100%)', padding: '20px', color: 'white', position: 'relative', flexShrink: 0 }}>
                            <button onClick={() => setSelectedReceipt(null)} style={{ position: 'absolute', top: '15px', right: '15px', background: 'rgba(255,255,255,0.2)', border: 'none', borderRadius: '50%', width: '30px', height: '30px', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', color: 'white' }}><X size={16}/></button>
                            <div style={{ textAlign: 'center', marginTop: '10px' }}>
                                <div style={{ background: 'rgba(255,255,255,0.15)', width: '50px', height: '50px', borderRadius: '14px', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 10px' }}><CheckCircle size={28} color="#4ade80" /></div>
                                <h2 style={{ margin: 0, fontSize: '1.5rem', fontWeight: '700' }}>₹{Number(selectedReceipt.amount).toLocaleString()}</h2>
                                <p style={{ margin: '5px 0 0', opacity: 0.8, fontSize: '0.9rem' }}>Payment Successful</p>
                            </div>
                        </div>
                        <div style={{ padding: '25px', overflowY: 'auto', flex: 1 }}>
                            <div style={receiptRow}><span style={receiptLabel}>Transaction ID</span><span style={receiptValue}>TXN-{selectedReceipt.id}8829</span></div>
                            <div style={receiptRow}><span style={receiptLabel}>Staff Name</span><span style={receiptValue}>{selectedReceipt.staff_name}</span></div>
                            <div style={receiptRow}><span style={receiptLabel}>Role</span><span style={receiptValue}>{selectedReceipt.role}</span></div>
                            <div style={receiptRow}><span style={receiptLabel}>Month</span><span style={receiptValue}>{selectedReceipt.month}</span></div>
                            <div style={receiptRow}><span style={receiptLabel}>Date & Time</span><span style={receiptValue}>{new Date(selectedReceipt.payment_date).toLocaleString()}</span></div>
                            <div style={{ borderTop: '2px dashed #e2e8f0', margin: '20px 0' }}></div>
                            <div style={{ display: 'flex', gap: '10px' }}>
                                {/* 🔥 Buttons Connected */}
                                <button onClick={handlePrintReceipt} style={{ flex: 1, padding: '12px', borderRadius: '12px', border: '1px solid #e2e8f0', background: 'white', color: '#1e293b', fontWeight: '700', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' }}><Printer size={16}/> Print</button>
                                <button onClick={handleDownloadReceipt} style={{ flex: 1, padding: '12px', borderRadius: '12px', border: 'none', background: '#4f46e5', color: 'white', fontWeight: '700', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' }}><FileText size={16}/> Download</button>
                            </div>
                        </div>
                    </motion.div>
                </div>
            )}
        </AnimatePresence>
      </div>

      {/* 🚀 CSS FOR 100% RESPONSIVENESS AND ALIGNMENT FIXES */}
      <style>{`
        /* Avoid Body scroll locking globally */
        html, body, #root { margin: 0; padding: 0; height: 100%; }

        .payroll-page-wrapper {
            display: flex;
            width: 100%;
            height: 100vh;
            overflow: hidden;
            background: #f8fafc;
            font-family: 'Inter', sans-serif;
        }

        .payroll-main-content {
            flex: 1;
            margin-left: 280px; 
            padding: 30px;
            padding-bottom: 120px !important; /* Prevents Chatbot overlap on desktop */
            height: 100vh;
            overflow-y: auto !important; /* Desktop Scroll Guarantee */
            box-sizing: border-box;
            max-width: calc(100% - 280px);
            position: relative;
            z-index: 1;
        }

        .page-header { display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 25px; }
        .header-actions { display: flex; gap: 10px; }

        .stats-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-bottom: 30px; width: 100%; }
        
        /* ✅ FIXED: Changed to Flexbox for Desktop layout stability */
        .content-flex-container { 
            display: flex; 
            flex-direction: row; 
            gap: 25px; 
            align-items: flex-start; 
            width: 100%; 
        }

        .form-panel {
            width: 350px; /* Fixed sleek width for Desktop */
            flex-shrink: 0; 
        }

        .table-panel {
            flex: 1; /* Takes remaining width */
            min-width: 0; /* Prevents flex blowout */
        }

        .grid-2-col { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; width: 100%; }

        /* ✅ TABLE HORIZONTAL SCROLL FIX */
        .table-wrapper {
            overflow-x: auto;
            width: 100%;
            -webkit-overflow-scrolling: touch;
            padding: 0 5px;
            display: block;
        }

        /* 📱 RESPONSIVE MEDIA QUERIES */
        @media (max-width: 1024px) {
            .payroll-main-content { margin-left: 0 !important; max-width: 100%; width: 100%; }
        }

        @media (max-width: 850px) {
            /* Unlock Scroll on Mobile completely */
            html, body, #root { height: auto !important; min-height: 100vh !important; overflow-y: visible !important; }
            
            .payroll-page-wrapper {
                display: block !important; 
                height: auto !important;
                min-height: 100vh !important;
            }

            .payroll-main-content {
                margin-left: 0 !important;
                padding: 15px !important;
                padding-top: 85px !important; 
                padding-bottom: 180px !important; 
                width: 100vw !important;
                max-width: 100vw !important;
                height: auto !important;
                min-height: 100vh !important;
                overflow: visible !important;
                display: block !important; /* Break Flex lock */
            }

            .pagination-container { margin-bottom: 40px !important; }
            .page-header { flex-direction: column; align-items: flex-start !important; gap: 15px; }
            .header-actions { width: 100%; }
            .header-actions button { flex: 1; justify-content: center; }

            .stats-grid { grid-template-columns: 1fr !important; }
            
            /* ✅ FIXED: Mobile view changes row to column */
            .content-flex-container { 
                flex-direction: column !important; 
            }
            
            .form-panel { 
                width: 100% !important; /* Full width on mobile */
                margin-bottom: 20px !important; 
            }

            .table-panel { width: 100% !important; }
        }
      `}</style>
    </div>
  );
}

// ✨ Styles
const primaryBtnStyle = { display: 'flex', alignItems: 'center', gap: '6px', background: '#0f172a', border: 'none', padding: '8px 15px', borderRadius: '8px', fontWeight: '700', color: 'white', cursor: 'pointer', fontSize: '0.85rem' };
const secondaryBtnStyle = { display: 'flex', alignItems: 'center', gap: '6px', background: 'white', border: '1px solid #e2e8f0', padding: '8px 15px', borderRadius: '8px', fontWeight: '700', color: '#475569', cursor: 'pointer', fontSize: '0.85rem' };

// ✅ FIXED: Button Text Perfectly Centered
const actionGlowBtnStyle = { 
    background: "linear-gradient(to right, #6366f1, #8b5cf6)", 
    color: "white", 
    border: "none", 
    borderRadius: "10px", 
    cursor: "pointer", 
    fontWeight: "700", 
    padding: "12px", 
    fontSize: '0.95rem', 
    width: '100%', 
    marginTop: '10px', 
    boxShadow: '0 6px 15px -5px rgba(99, 102, 241, 0.4)',
    display: 'flex',             // Flexbox for centering
    justifyContent: 'center',    // Center Horizontally
    alignItems: 'center',        // Center Vertically
    boxSizing: 'border-box'
};

const heroStatCardStyle = { background: 'linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)', padding: "20px", borderRadius: "16px", position: 'relative', overflow: 'hidden', boxShadow: '0 8px 20px -5px rgba(79, 70, 229, 0.3)', width: '100%', boxSizing: 'border-box' };
const glassStatCardStyle = { background: "white", padding: "20px", borderRadius: "16px", boxShadow: "0 4px 6px rgba(0, 0, 0, 0.02)", border: '1px solid #f1f5f9', width: '100%', boxSizing: 'border-box' };
const glassPanelStyle = { background: "white", padding: "20px", borderRadius: "20px", boxShadow: "0 8px 25px -5px rgba(0, 0, 0, 0.04)", border: '1px solid #f1f5f9', boxSizing: 'border-box' };
const inputGroupStyle = { marginBottom: '4px' };
const labelStyle = { display: 'block', fontSize: '0.8rem', color: '#475569', fontWeight: '700', margin: '0 0 4px 0' };
const inputStyle = { border: '1px solid #e2e8f0', borderRadius: '10px', width: '100%', padding: '10px', fontSize: '0.9rem', color: '#1e293b', background: '#f8fafc', fontWeight: '600', outline: 'none', boxSizing: 'border-box' };
const thStyle = { padding: "10px 15px", textAlign: "left", color: "#94a3b8", fontSize: "0.7rem", fontWeight: '800', textTransform: 'uppercase', whiteSpace: 'nowrap' };
const tdStyle = { padding: "12px 15px", verticalAlign: 'middle' };
const floatingRowStyle = { background: 'white', borderRadius: '12px', transition: 'all 0.2s', border: '1px solid #f1f5f9' };
const avatarStyle = { width: '32px', height: '32px', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '800', fontSize: '0.9rem', flexShrink: 0 };
const cardLabelStyle = { color: '#64748b', fontSize: '0.8rem', fontWeight: '600', margin: '0 0 4px 0' };
const cardValueStyle = { color: '#0f172a', fontSize: '1.6rem', fontWeight: '800', margin: 0 };
const receiptRow = { display: 'flex', justifyContent: 'space-between', margin: '0 0 12px 0' };
const receiptLabel = { color: '#64748b', fontSize: '0.9rem', fontWeight: '600' };
const receiptValue = { color: '#1e293b', fontSize: '0.9rem', fontWeight: '700' };