# Generated by Django 6.0.2 on 2026-02-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='allocated_mb',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='visitor',
            name='id_proof',
            field=models.CharField(blank=True, help_text='Aadhar/PAN No.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='photo',
            field=models.TextField(blank=True, help_text='Stores Base64 Image Data from Webcam', null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='place_id',
            field=models.CharField(default='IND-UP-JAUNPUR-01', max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='virtual_id',
            field=models.CharField(default='V-SEC-001', max_length=50),
        ),
    ]
