# Generated by Django 6.0.2 on 2026-03-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_visitor_address_visitor_allocated_mb_visitor_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='accompanying_persons',
            field=models.IntegerField(default=0, help_text='Number of people accompanying the visitor'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='id_proof_file',
            field=models.FileField(blank=True, help_text='Uploaded ID Document (Image/PDF)', null=True, upload_to='visitor_ids/'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Optional Vehicle Number', max_length=30, null=True),
        ),
    ]
