# Generated by Django 6.0.2 on 2026-02-09 19:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hierarchy_code', models.CharField(blank=True, help_text='Auto: 0.1.1.1', max_length=100)),
                ('virtual_id', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('place_type', models.CharField(choices=[('Global', 'Global'), ('Continent', 'Continent'), ('Country', 'Country'), ('State', 'State'), ('District', 'District'), ('Tehsil', 'Tehsil'), ('Block', 'Block'), ('Village', 'Village'), ('School', 'School/Center')], default='Global', max_length=50)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='locations.place')),
            ],
            options={
                'ordering': ['hierarchy_code'],
            },
        ),
    ]
