# Generated by Django 6.0.2 on 2026-02-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='beat_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='google_map_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='pin_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='place_uses_for',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='space_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='village_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='work_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('Global', 'Global'), ('Continent', 'Continent'), ('Country', 'Country'), ('State', 'State'), ('District', 'District'), ('Tehsil', 'Tehsil'), ('Block', 'Block'), ('Colony', 'Colony'), ('Village', 'Village'), ('School', 'School/Center')], default='Global', max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activate'), ('DEACTIVATED', 'Deactivate'), ('HIDDEN', 'Hibernate/Hide')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='virtual_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
