# Generated by Django 6.0.2 on 2026-02-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_place_beat_no_place_google_map_id_place_pin_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active / Show'), ('INACTIVE', 'Inactive / Hide')], default='ACTIVE', max_length=20),
        ),
    ]
