# Generated by Django 6.0.2 on 2026-03-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_place_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_uses_for',
            field=models.CharField(blank=True, choices=[('None', '-- Uses For --'), ('Foundation', 'Foundation'), ('Preparatory', 'Preparatory'), ('Middle', 'Middle'), ('Secondary', 'Secondary'), ('Higher Classes', 'Higher Classes'), ('PHD Plus', 'PHD Plus'), ('Professional', 'Professional'), ('Technical', 'Technical'), ('Vacational', 'Vacational'), ('Academic Professional', 'Academic Professional'), ('Academic and Technical', 'Academic & Technical'), ('Academic Vacational', 'Academic Vacational'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='space_type',
            field=models.CharField(blank=True, choices=[('Physical', 'Physical Space'), ('Virtual', 'Virtual Space')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='work_status',
            field=models.CharField(blank=True, choices=[('Ministerial Office', 'Ministerial Office'), ('Working Fields', 'Working Fields'), ('Both', 'Both (Office + Field)'), ('None', 'None')], max_length=50, null=True),
        ),
    ]
