# Generated by Django 6.0.2 on 2026-05-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_place_place_uses_for_alter_place_space_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='branch_code',
            field=models.IntegerField(blank=True, help_text='0 से 7 तक ब्रांच/लोकेशन कोड', null=True),
        ),
    ]
