# Generated by Django 6.0.2 on 2026-02-09 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('institution_code', models.CharField(blank=True, help_text='e.g., BR-01', max_length=50, null=True, unique=True)),
                ('principal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('address_details', models.TextField(blank=True, help_text='Full street address', null=True)),
                ('subscription_plan', models.CharField(choices=[('FREE', 'Free Trial'), ('BASIC', 'Basic Plan'), ('PREMIUM', 'Premium Plan')], default='FREE', max_length=10)),
                ('plan_start_date', models.DateTimeField(auto_now_add=True)),
                ('plan_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('virtual_id', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('levels', models.ManyToManyField(blank=True, to='services.educationlevel')),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_institution', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='locations.place')),
                ('service_mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='services.servicemode')),
                ('service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='services.servicetype')),
            ],
        ),
    ]
