# Generated by Django 6.0.2 on 2026-02-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='has_hostel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='has_library',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='has_security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='has_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='management_type',
            field=models.CharField(blank=True, choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('COMPANY', 'Company'), ('TRUST', 'Trust'), ('NGO', 'NGO')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='pin_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='place_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='tech_used',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
