# Generated by Django 6.0.2 on 2026-02-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=15)),
                ('route_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('Bus', 'Bus'), ('Van', 'Van')], max_length=50)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
